<?php
error_reporting(E_ALL);
ini_set('display_errors', 'On');
require_once 'bootstrap.php';
require_once 'EmissorNFe.php';

//tanto o config.json como o certificado.pfx podem estar
//armazenados em uma base de dados, então não é necessário
///trabalhar com arquivos, este script abaixo serve apenas como
//exemplo durante a fase de desenvolvimento e testes.
$arr = [
    "atualizacao" => "2017-11-27 21:25:00",
    "tpAmb" => 2,
    "razaosocial" => "FERNANDA WITZGALL ME",
    "cnpj" => "21996226000164",
    "siglaUF" => "RS",
    "schemes" => "PL008i2",
    "versao" => '3.10',
    "tokenIBPT" => "",
    "CSC" => "F8D212EF010646CA9B7048BA1707D335",
    "CSCid" => "000001",
    "proxyConf" => [
        "proxyIp" => "",
        "proxyConf" => "",
        "proxyUser" => "",
        "proxyPass" => ""
    ]
];

$dadosNfe = [
    "tpAmb" => "2",
    "cDV" => "",
    "id" => "NFe35150271780456000160550010000000021800700082",
    "mod" => "55",
    "cNF" => "12346789",
    "cUF" => "43",
    "natOp" => "VENDA",
    "indPag" => "1",
    "serie" => "1",
    "nNF" => "123",
    "dhEmi" => "2015-02-19T13:48:00-02:00",
    "dhSaiEnt" => null,
    "tpNF" => "1",
    "idDest" => "1",
    "cMunFG" => "4307005",
    "tpImp" => "1",
    "tpEmis" => "1",
    "finNFe" => "1",
    "indFinal" => "0",
    "indPres" => "9",
    "procEmi" => "0",
    "verProc" => "1.0.0",
    "xNome" => "FERNANDA WITZGALL ME",
    "xFant" => "Clínica Veterinária Fernanda Witzgall",
    "IE" => "0390174319",
    "IEST" => null,
    "IM" => null,
    "CNAE" => null,
    "CRT" => 1,
    "xLgr" => "Rua Torres Gonçalves",
    "nro" => "156",
    "xCpl" => null,
    "xBairro" => "Centro",
    "cMun" => "4307005",
    "xMun" => "Erechim",
    "UF" => "RS",
    "CEP" => "99700422",
    "cPais" => "1058",
    "xPais" => "Brasil",
    "fone" => "5499683888",
    "vBC" => null,
    "vICMS" => null,
    "vICMSDesonv" => null,
    "vBCST" => null,
    "vST" => null,
    "vProd" => 100.00,
    "vFrete" => null,
    "vSeg" => null,
    "vDesc" => null,
    "vII" => null,
    "vIPI" => null,
    "vPIS" => null,
    "vCOFINS" => null,
    "vOutro" => null,
    "vNF" => 100.00,
    "vTotTrib" => null,
    "vFCP" => null,
    "vFCPST" => null,
    "vFCPSTRet" => null,
    "vIPIDevol" => null,
    "modFrete" => 1,
    "tPag" => "01",
    "vPag" => 100.00,
    "tpIntegra" => 2,
    "vTroco" => null,
    "doctoNfe" => [
      "doc" => "CNPJ",
      "CNPJ" => "21996226000164",
      "CPF" => null,
    ],
    "usaNfeCartaoCredito" => [
      "Cartao" => false,
      "CNPJ" => null,
      "tBand" => "02",
      "cAut" => null,
    ],
    "destinatario" => [
      "xNome" => "Guilherme Afonso Madalozzo",
      "indIEDest" => "9",
      "IE" => null,
      "ISUF" => null,
      "IM" => null,
      "email" => "guimadalozzo@gmail.com",
      "idEstrangeiro" => null,
      "xLgr" => "Rua João Paulo I",
      "nro" => 585,
      "xCpl" => null,
      "xBairro" => "Três Vendas",
      "cMun" => "4307005",
      "xMun" => "Erechim",
      "UF" => "RS",
      "CEP" => "99713220",
      "cPais" => "1058",
      "xPais" => "BRASIL",
      "fone" => "54996227898",
      "doctoNfe" => [
        "doc" => "CPF",
        "CNPJ" => null,
        "CPF" => "01852675055",
      ],
      "endEntrega" => [
        "xLgr" => "Rua João Paulo I",
        "nro" => 585,
        "xCpl" => null,
        "xBairro" => "Três Vendas",
        "cMun" => "4307005",
        "xMun" => "Erechim",
        "UF" => "RS",
        "doctoNfe" => [
          "doc" => "CPF",
          "CNPJ" => null,
          "CPF" => "01852675055",
        ],
      ],
      "endRetirada" => [
        "retirada" => false,
        "xLgr" => null,
        "nro" => null,
        "xCpl" => null,
        "xBairro" => null,
        "cMun" => null,
        "xMun" => null,
        "UF" => null,
        "doctoNfe" => [
          "doc" => null,
          "CNPJ" => null,
          "CPF" => null,
        ],
      ],
    ],
    "usaNfContingencia" => [
      "contingencia" => false,
      "dhCont" => "2015-02-19T13:48:00-02:00",
      "xJust" => "Justificativa da contingencuia",
    ],
    "usaNfReferenciada" => [
      "referenciada" => false,
      "refNFe" => "35150271780456000160550010000253101000253101",
    ],
    "usaNfISSQN" => [
      "ISSQN" => false,
    ],
    "usaNfRetTributos" => [
      "RetTributos" => false,
    ],
    "usaNfTransportadora" => [
      "Transportadora" => false,
      "xNome" => null,
      "IE" => null,
      "xEnder" => null,
      "xMun" => null,
      "UF" => null,
      "CNPJ" => null,
      "CPF" => null,
      "usaNfVolumeTransportadora" => [
        "Volume" => false,
        1 => [
          "item" => "1",
          "qVol" => "2",
          "esp" => "caixa",
          "marca" => null,
          "nVol" => null,
          "pesoL" => null,
          "pesoB" => null,
        ],
      ],
    ],
    "usaNfDetalheVeicTransportadora" => [
      "Veiculo" => false,
    ],
    "usaNfReboqueVeicTransportadora" => [
      "Reboque" => false,
    ],
    "usaNfDadosFatura" => [
      "Fatura" => false,
      "nFat" => null,
      "vOrig" => null,
      "vDesc" => null,
      "vLiq" => null,
    ],
    "usaNfDadosDuplicata" => [
      "Duplicata" => false,
      "nDup" => null,
      "dVenc" => null,
      "vDup" => null,
    ],
    "usaNfExportacao" => [
      "Exportacao" => false,
    ],
    "infAdFisco" => null,
    "infCpl" => null,
    "qtdItens" => "1",
];

$dadosNfeItens = [
  1 => [
    "item" => 1,
    "cProd" => 1,
    "cEAN" => null,
    "xProd" => "Vanguard Plus 1DS",
    "NCM" => "30023090",
    "EXTIPI" => null,
    "CFOP" => "5102",
    "uCom" => "UN",
    "qCom" => 1,
    "vUnCom" => 55.00,
    "vProd" => 55.00,
    "cEANTrib" => null,
    "uTrib" => "UN",
    "qTrib" => 1,
    "vUnTrib" => 55.00,
    "vFrete" => null,
    "vSeg" => null,
    "vDesc" => null,
    "vOutro" => null,
    "indTot" => 1,
    "xPed" => null,
    "nItemPed" => null,
    "nFCI" => null,
    "infAdProd" => "Informações adicionais do produto.",
    "CEST" => null,
    "indEscala" => null,
    "CNPJFab" => null,
    "nLote" => null,
    "qLote" => null,
    "dFab" => null,
    "dVal" => null,
    "cAgreg" => null,
    "vTotTrib" => 0.00,
    "orig" => "0",
    "CST" => "40",
    "modBC" => null,
    "vBC" => null,
    "pICMS" => null,
    "vICMS" => null,
    "pFCP" => null,
    "vFCP" => null,
    "vBCFCP" => null,
    "modBCST" => null,
    "pMVAST" => null,
    "pRedBCST" => null,
    "vBCST" => null,
    "pICMSST" => null,
    "vICMSST" => null,
    "vBCFCPST" => null,
    "pFCPST" => null,
    "vFCPST" => null,
    "vICMSDeson" => null,
    "motDesICMS" => null,
    "pRedBC" => null,
    "vICMSOp" => null,
    "pDif" => null,
    "vICMSDif" => null,
    "vBCSTRet" => null,
    "pST" => null,
    "vICMSSTRet" => null,
    "vBCFCPSTRet" => null,
    "pFCPSTRet" => null,
    "vFCPSTRet" => null,
    "pBCOp" => null,
    "UFST" => null,
    "vBCSTDest" => null,
    "vICMSSTDest" => null,
    "CSOSN" => "400",
    "pCredSN" => null,
    "vCredICMSSN" => null,
    "vBCUFDest" => null,
    "vBCFCPUFDest" => null,
    "pFCPUFDest" => null,
    "pICMSUFDest" => null,
    "pICMSInter" => null,
    "pICMSInterPart" => null,
    "vFCPUFDest" => 0.00,
    "vICMSUFDest" => null,
    "vICMSUFRemet" => null,
    "pPIS" => null,
    "vPIS" => null,
    "qBCProd" => null,
    "vAliqProd" => null,
    "pCOFINS" => null,
    "vCOFINS" => null,
    "qBCProd" => null,
    "vAliqProd" => null,
    "pDevol" => null,
    "vIPIDevol" => null,
    "usaNfDevolucao" => [
      "Devolucao" => false,
    ],
    "usaNfISSQN" => [
      "ISSQN" => false,
    ],
    "usaNfCOFINSST" => [
      "cofinsST" => false,
    ],
    "usaNfTributacaoCOFINS" => [
      "cofins" => false,
    ],
    "usaNfPISST" => [
      "pisST" => false,
    ],
    "usaNfPIS" => [
      "PIS" => false,
    ],
    "usaNfIPI" => [
      "IPI" => false,
    ],
    "usaNfII" => [
      "ImpostoImportacao" => false,
    ],
    "usaNfTributacaoSN" => [
      "TributaSN" => true,
    ],
    "usaNfICMSInterestadual" => [
      "ICMSInter" => false,
    ],
    "usaNfICMSRetido" => [
      "RetemICMS" => false,
    ],
    "usaNfPartilhaUF" => [
      "PartilhaUF" => false,
    ],
    "usaNfRecopi" => [
      "Recopi" => false,
    ],
    "usaNfDI" => [
      "DI" => false,
    ],
    "usaNfExportacao" => [
      "Exportacao" => false,
    ],
    "usaNfVeiculo" => [
      "Veiculo" => false,
    ],
    "usaNfMedicamentos" => [
      "Medicamento" => false,
      "nLote" => null,
      "qLote" => null,
      "dFab" => null,
      "dVal" => null,
      "vPMC" => null,
      "cProdANVISA" => null,
    ],
    "usaNfArmamento" => [
      "Armamento" => false,
    ],
    "usaNfCombustivel" => [
      "Combustivel" => false,
    ],
  ],
];

$configJson = json_encode($arr);
$dadosNfeJson = json_encode($dadosNfe);
$dadosNfeItensJson = json_encode($dadosNfeItens);
$emissor = new EmissorNFe($configJson, $dadosNfeJson, $dadosNfeItensJson);
$emissor->emiteNfe();

